/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem.handler;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author saman
 */
public class DeleteHandler extends javax.swing.JFrame {

    /**
     * Creates new form DeleteHandler
     */
    public DeleteHandler() {
        initComponents();
          // Group the radio buttons so only one can be selected at a time
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        
          // Initially hide the title and ISBN text fields
        titleField.setVisible(false);
        isbnField.setVisible(false);
        titleLabel.setVisible(false);
        isbnLabel.setVisible(false);
        
        // Set up event listeners for radio buttons
        jRadioButton1.addActionListener(evt -> {
            titleField.setVisible(true);
            isbnField.setVisible(false); // Hide ISBN field when Title is selected
            titleLabel.setVisible(true);
            isbnLabel.setVisible(false);
            titleField.setText(""); // Clear any previous input
        });

        jRadioButton2.addActionListener(evt -> {
            titleField.setVisible(false);
            isbnField.setVisible(true); // Show ISBN field when ISBN is selected
            titleLabel.setVisible(false);
            isbnLabel.setVisible(true);
            isbnField.setText(""); // Clear any previous input
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        deleteBook = new javax.swing.JButton();
        titleField = new javax.swing.JTextField();
        isbnField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Book");
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        deleteBook.setBackground(new java.awt.Color(153, 0, 153));
        deleteBook.setForeground(new java.awt.Color(255, 255, 255));
        deleteBook.setText("Delete Book");
        deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBook);
        deleteBook.setBounds(127, 258, 170, 40);
        getContentPane().add(titleField);
        titleField.setBounds(130, 170, 167, 30);
        getContentPane().add(isbnField);
        isbnField.setBounds(130, 168, 167, 30);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\saman\\Downloads\\icons8-add-32.png")); // NOI18N
        jLabel1.setText("Delete Books");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(153, 6, 243, 42);

        titleLabel.setText("Title:");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(130, 150, 37, 16);

        isbnLabel.setText("ISBN:");
        getContentPane().add(isbnLabel);
        isbnLabel.setBounds(130, 146, 37, 16);

        jRadioButton1.setText("Delete by Title");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(50, 90, 130, 21);

        jRadioButton2.setText("Delete by ISBN");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(260, 90, 120, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookActionPerformed
        String projectDir = System.getProperty("user.dir");
        String outputFilePath = projectDir + "/output/output.txt";
        File outputFile = new File(outputFilePath);

        String deleteByTitle = titleField.getText().trim();
        String deleteByIsbn = isbnField.getText().trim();

        // Ensure that either "Delete by Title" or "Delete by ISBN" is selected
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select either 'Delete by Title' or 'Delete by ISBN'.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jRadioButton1.isSelected() && deleteByTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the title of the book to delete.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jRadioButton2.isSelected() && deleteByIsbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the ISBN of the book to delete.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<String> remainingBooks = new ArrayList<>();
        boolean bookFound = false;

        // Read and filter books based on the deletion criteria
        try (BufferedReader reader = new BufferedReader(new FileReader(outputFile))) {
            String line;
            StringBuilder bookDetails = new StringBuilder();
            boolean isBookEntry = false;

            while ((line = reader.readLine()) != null) {
                if (line.startsWith("Title:")) {
                    if (isBookEntry) {
                        remainingBooks.add(bookDetails.toString());
                        bookDetails.setLength(0);
                    }
                    isBookEntry = true;
                }

                bookDetails.append(line).append(System.lineSeparator());

                if (jRadioButton1.isSelected() && line.startsWith("Title: " + deleteByTitle)) {
                    bookFound = true;
                    isBookEntry = false; // Skip this book entry for deletion
                } else if (jRadioButton2.isSelected() && line.startsWith("ISBN: " + deleteByIsbn)) {
                    bookFound = true;
                    isBookEntry = false; // Skip this book entry for deletion
                }
            }
            if (isBookEntry) {
                remainingBooks.add(bookDetails.toString());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading 'output.txt': " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Write remaining books back to the file
        if (bookFound) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
                for (String book : remainingBooks) {
                    writer.write(book);
                }
                JOptionPane.showMessageDialog(this, "Book deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error writing to 'output.txt': " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Book not found based on the selected criteria.", "Not Found", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteHandler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBook;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
